FROM python:3.13-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./
RUN chmod +x ./docker-entrypoint.sh
EXPOSE 5000

ENTRYPOINT ["./docker-entrypoint.sh"]
